server:
  port: 6677 #服务端口

spring: 
  application:  
    name: itcasst-microservice-api-gateway #指定服务名
    
zuul: 
  routes: 
    item-service: #item-service这个名字是任意写的
      path: /item-service/** #配置请求URL的请求规则
      #url: http://127.0.0.1:8181 #真正的微服务地址
      serviceId: itcast-microservice-item #指定Eureka注册中心中的服务id

eureka:
  client:
    registerWithEureka: true #是否将自己注册到Eureka服务中，默认为true
    fetchRegistry: true #是否从Eureka中获取注册信息，默认为true
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://itcast:itcast123@127.0.0.1:6868/eureka/
  instance: 
    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
